# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o0Kmkpltd-_XPfw2Tb54MPD3JWp1r1m8
"""

from bs4 import BeautifulSoup as soup
from urllib.request import urlopen, Request
import pandas as pd
import code as code

code= code.Code()
code.scrape_website("https://www.scrapethissite.com/pages/forms/", "team")
code.data_to_csv()